version: '3.8'

services:
  app:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=hackaton2006
      - MYSQL_DB=hackaton
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hackaton2006
      MYSQL_DATABASE: hackaton
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-phackaton2006"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  db_data: